application: crowdstart-io
module: default
version: v17

runtime: go
api_version: go1
threadsafe: true

inbound_services:
- warmup

handlers:
- url: /_ah/.*
  script: _go_app

- url: /css/*
  static_dir: static/css

- url: /js/*
  static_dir: static/js

- url: /img/*
  static_dir: static/img

- url: /adminlte/*
  static_dir: static/adminlte

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /humans.txt
  static_files: static/humans.txt
  upload: static/humans.txt

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
