application: crowdstart-io

dispatch:
  - url: "api.crowdstart.io/*"
    module: api

  - url: "secure.crowdstart.io/*"
    module: checkout

  - url: "platform.crowdstart.io/*"
    module: platform

  - url: "preorder.crowdstart.io/*"
    module: preorder

  - url: "store.crowdstart.io/*"
    module: store

  - url: "static.crowdstart.io/*"
    module: default

  - url: "*/robots.txt"
    module: default

  - url: "*/humans.txt"
    module: default

  - url: "*/apple-touch-icon.png"
    module: default

  - url: "*/apple-touch-icon-precomposed.png"
    module: default

