application: crowdstart-io

dispatch:
  - url: "static.crowdstart.io/*"
    module: default

  - url: "*/robots.txt"
    module: default

  - url: "*/humans.txt"
    module: default

  - url: "*/favicon.ico"
    module: default

  - url: "api.crowdstart.io/*"
    module: api

  - url: "platform.crowdstart.io/*"
    module: platform

  - url: "preorder.skullysystems.com/*"
    module: preorder

  - url: "store.crowdstart.io/*"
    module: store

  - url: "secure.crowdstart.io/*"
    module: checkout
