application: crowdstart-io

dispatch:
  - url: "api.crowdstart.io/*"
    module: api

  - url: "platform.crowdstart.io/*"
    module: platform

  - url: "preorder.crowdstart.io/*"
    module: preorder

  - url: "store.crowdstart.io/*"
    module: store

  - url: "secure.crowdstart.io/*"
    module: checkout

  - url: "*/css/*"
    module: default

  - url: "*/js/*"
    module: default

  - url: "*/img/*"
    module: default

  - url: "*/robots.txt"
    module: default

  # - url: "*/humans.txt"
  #   module: default

  - url: "*/favicon.ico"
    module: default

  # - url: "*/"
  #   module: default
