application: crowdstart-staging

dispatch:
  - url: "default.staging.hanzo.io/*"
    module: default

  - url: "js.staging.hanzo.io/*"
    module: default

  - url: "static.staging.hanzo.io/*"
    module: default

  - url: "api.staging.hanzo.io/*"
    module: api

  - url: "cdn.staging.hanzo.io/*"
    module: cdn

  - url: "platform.staging.hanzo.io/*"
    module: platform
