dispatch:
  - url: "default-staging.hanzo.io/*"
    service: default

  - url: "static-staging.hanzo.io/*"
    service: default

  - url: "analytics-staging.hanzo.io/*"
    service: analytics

  - url: "api-staging.hanzo.io/*"
    service: api

  - url: "cdn-staging.hanzo.io/*"
    service: api

  - url: "dash-staging.hanzo.io/*"
    service: dash
