application: crowdstart-staging

dispatch:
  - url: "default.staging.crowdstart.com/*"
    module: default

  - url: "js.staging.crowdstart.com/*"
    module: default

  - url: "static.staging.crowdstart.com/*"
    module: default

  - url: "api.staging.crowdstart.com/*"
    module: api

  - url: "cdn.staging.crowdstart.com/*"
    module: cdn

  - url: "platform.staging.crowdstart.com/*"
    module: platform
