application: crowdstart-staging

dispatch:
  - url: "api-dot-crowdstart-staging.appspot.com/*"
    module: api

  - url: "checkout-dot-crowdstart-staging.appspot.com/*"
    module: checkout

  - url: "default-dot-crowdstart-staging.appspot.com/*"
    module: default

  - url: "static-dot-crowdstart-staging.appspot.com/*"
    module: default

  - url: "platform-dot-crowdstart-staging.appspot.com/*"
    module: platform

  - url: "preorder-dot-crowdstart-staging.appspot.com/*"
    module: preorder

  - url: "store-dot-crowdstart-staging.appspot.com/*"
    module: store
