application: crowdstart-staging

dispatch:
  - url: "default-staging.hanzo.io/*"
    module: default

  - url: "static-staging.hanzo.io/*"
    module: default

  - url: "analytics-staging.hanzo.io/*"
    module: analytics

  - url: "api-staging.hanzo.io/*"
    module: api

  - url: "cdn-staging.hanzo.io/*"
    module: api

  - url: "dash-staging.hanzo.io/*"
    module: dash
