dispatch:
  - url: "default-staging.hanzo.ai/*"
    service: default

  - url: "js-staging.hanzo.ai/*"
    service: default

  - url: "static-staging.hanzo.ai/*"
    service: default

  - url: "analytics-staging.hanzo.ai/*"
    service: analytics

  - url: "api-staging.hanzo.ai/*"
    service: api

  - url: "cdn-staging.hanzo.ai/*"
    service: api

  - url: "x-staging.hanzo.ai/*"
    service: api
