apiVersion: v1
kind: Service
metadata:
  name: commerce
  namespace: hanzo
  labels:
    app: commerce
spec:
  type: ClusterIP
  ports:
    - port: 8001
      targetPort: 8001
      protocol: TCP
  selector:
    app: commerce
