application: crowdstart-skully

dispatch:
  - url: "static.skully.com/*"
    module: default

  - url: "store.skully.com/*"
    module: store

  - url: "secure.skully.com/*"
    module: checkout

  - url: "preorder.skully.com/*"
    module: preorder

  - url: "api.skully.com/*"
    module: platform
