application: crowdstart-io

dispatch:
  - url: "*/_ah/queue/go/delay"
    module: default

  - url: "*/api/*"
    module: api

  - url: "*/checkout/*"
    module: checkout

  - url: "*/admin/*"
    module: platform

  - url: "*/preorder/*"
    module: preorder

  - url: "*/store/*"
    module: store

  - url: "*/static/*"
    module: default

  - url: "*/assets/*"
    module: default

  - url: "*/robots.txt"
    module: default

  - url: "*/humans.txt"
    module: default

  - url: "*/apple-touch-icon.png"
    module: default

  - url: "*/apple-touch-icon-precomposed.png"
    module: default
