application: crowdstart-us

dispatch:
  - url: "*/api/*"
    module: api

  - url: "*/dash/*"
    module: dash

  - url: "*/default/*"
    module: default

  - url: "*/static/*"
    module: default

  - url: "*/assets/*"
    module: default

  - url: "*/robots.txt"
    module: default

  - url: "*/humans.txt"
    module: default

  - url: "*/apple-touch-icon.png"
    module: default

  - url: "*/apple-touch-icon-precomposed.png"
    module: default
