application: crowdstart-us

dispatch:
  - url: "*/api/*"
    module: api

  # - url: "*/checkout/*"
  #   module: checkout

  - url: "*/analytics/*"
    module: analytics

  - url: "*/admin/*"
    module: platform

  - url: "*/platform/*"
    module: platform

  # - url: "*/preorder/*"
  #   module: preorder

  - url: "*/store/*"
    module: store

  - url: "*/default/*"
    module: default

  - url: "*/static/*"
    module: default

  - url: "*/assets/*"
    module: default

  - url: "*/robots.txt"
    module: default

  - url: "*/humans.txt"
    module: default

  - url: "*/apple-touch-icon.png"
    module: default

  - url: "*/apple-touch-icon-precomposed.png"
    module: default
