indexes:

- kind: user
  ancestor: no
  properties:
  - name: Email
  - name: CreatedAt
    direction: desc

- kind: _countershard
  ancestor: no
  properties:
  - name: Tag
  - name: StoreId
  - name: Geo
  - name: Period
  - name: Time

- kind: note
  ancestor: no
  properties:
  - name: Enabled
  - name: Time

- kind: event
  ancestor: no
  properties:
  - name: Type
  - name: CalculatedTimestamp
    direction: desc

- kind: event
  ancestor: no
  properties:
  - name: UserId
  - name: CalculatedTimestamp
    direction: desc

- kind: event
  ancestor: no
  properties:
  - name: SessionId
  - name: CalculatedTimestamp
    direction: desc

- kind: event
  ancestor: no
  properties:
  - name: PageId
  - name: CalculatedTimestamp
    direction: desc

- kind: event
  ancestor: no
  properties:
  - name: Event
  - name: CalculatedTimestamp
    direction: desc

- kind: event
  ancestor: no
  properties:
  - name: SessionId
  - name: Name
  - name: CalculatedTimestamp
    direction: desc

- kind: payment
  properties:
  - name: __key__
    direction: desc

- kind: copy
  ancestor: no
  properties:
  - name: Type
  - name: AdId

- kind: copy
  ancestor: no
  properties:
  - name: Type
  - name: AdSetId

- kind: block
  ancestor: no
  properties:
  - name: Type
  - name: CreatedAt
    direction: desc

- kind: block
  ancestor: no
  properties:
  - name: Type
  - name: Status
  - name: EthereumBlockNumber
    direction: desc

- kind: block
  ancestor: no
  properties:
  - name: Type
  - name: Status
  - name: BitcoinBlockNumber
    direction: desc

- kind: blockaddress
  ancestor: no
  properties:
  - name: Type
  - name: CreatedAt
    direction: desc

- kind: blocktransaction
  ancestor: no
  properties:
  - name: Type
  - name: CreatedAt
    direction: desc

- kind: blocktransaction
  ancestor: no
  properties:
  - name: Type
  - name: EthereumTransactionBlockNumber
  - name: Address
    direction: desc
