indexes:

- kind: user
  ancestor: no
  properties:
  - name: Email
  - name: CreatedAt
    direction: desc

- kind: _countershard
  ancestor: no
  properties:
  - name: Tag
  - name: StoreId
  - name: Geo
  - name: Period
  - name: Time

- kind: note
  ancestor: no
  properties:
  - name: Enabled
  - name: Time

- kind: event
  ancestor: no
  properties:
  - name: Type
  - name: CalculatedTimestamp
    direction: desc

- kind: event
  ancestor: no
  properties:
  - name: UserId
  - name: CalculatedTimestamp
    direction: desc

- kind: event
  ancestor: no
  properties:
  - name: SessionId
  - name: CalculatedTimestamp
    direction: desc

- kind: event
  ancestor: no
  properties:
  - name: PageId
  - name: CalculatedTimestamp
    direction: desc

- kind: event
  ancestor: no
  properties:
  - name: Event
  - name: CalculatedTimestamp
    direction: desc

- kind: event
  ancestor: no
  properties:
  - name: SessionId
  - name: Name
  - name: CalculatedTimestamp
    direction: desc

- kind: payment
  properties:
  - name: __key__
    direction: desc

- kind: copy
  ancestor: no
  properties:
  - name: Type
  - name: AdId

- kind: copy
  ancestor: no
  properties:
  - name: Type
  - name: AdSetId

- kind: block
  ancestor: no
  properties:
  - name: Type
  - name: CreatedAt
    direction: desc

- kind: block
  ancestor: no
  properties:
  - name: Type
  - name: EthereumBlockNumber
    direction: desc

- kind: block
  ancestor: no
  properties:
  - name: Type
  - name: Status
  - name: EthereumBlockNumber
    direction: desc

- kind: block
  ancestor: no
  properties:
  - name: Type
  - name: BitcoinBlockHeight
    direction: desc

- kind: block
  ancestor: no
  properties:
  - name: Type
  - name: Status
  - name: BitcoinBlockHeight
    direction: desc

- kind: blockaddress
  ancestor: no
  properties:
  - name: Type
  - name: CreatedAt
    direction: desc

- kind: blockaddress
  ancestor: no
  properties:
  - name: Type
  - name: Address

- kind: blocktransaction
  ancestor: no
  properties:
  - name: Type
  - name: CreatedAt
    direction: desc

- kind: blocktransaction
  ancestor: no
  properties:
  - name: Type
  - name: EthereumTransactionBlockNumber
    direction: desc

- kind: blocktransaction
  ancestor: no
  properties:
  - name: Type
  - name: EthereumTransactionFrom
  - name: EthereumTransactionNonce
    direction: desc

- kind: blocktransaction
  ancestor: no
  properties:
  - name: Type
  - name: BitcoinTransactionBlockHeight
    direction: desc

- kind: blocktransaction
  ancestor: no
  properties:
  - name: Type
  - name: BitcoinTransactionConfirmations
    direction: desc

- kind: blocktransaction
  ancestor: no
  properties:
  - name: BitcoinTransactionTxId
  - name: BitcoinTransactionVOutIndex

- kind: blocktransaction
  ancestor: no
  properties:
  - name: BitcoinTransactionType
  - name: BitcoinTransactionUsed
  - name: Address

- kind: transaction
  ancestor: no
  properties:
  - name: SourceKind
  - name: SourceId

- kind: transaction
  ancestor: no
  properties:
  - name: DestinationKind
  - name: DestinationId

- kind: transaction
  properties:
  - name: Test
  - name: SourceKind
  - name: SourceId
  - name: Currency

- kind: transaction
  properties:
  - name: Test
  - name: DestinationKind
  - name: DestinationId
  - name: Currency

- kind: referral
  properties:
  - name: Referrer.UserId
  - name: Revoked
