cron:
# - description: Datastore backup (hourly)
#   url: /_ah/datastore_admin/backup.create?name=automated_backup_hourly_&kind=bundle&kind=campaign&kind=collection&kind=coupon&kind=mailinglist&kind=namespace&kind=order&kind=organization&kind=payment&kind=plan&kind=product&kind=store&kind=subscriber&kind=token&kind=user&kind=variant&filesystem=gs&gs_bucket_name=crowdstart-us-backup
#   schedule: every 1 hours
#   target: ah-builtin-python-bundle

- description: Datastore backup (daily)
  url: /_ah/datastore_admin/backup.create?name=automated_backup_daily_&kind=bundle&kind=campaign&kind=collection&kind=coupon&kind=namespace&kind=order&kind=organization&kind=payment&kind=plan&kind=event&kind=product&kind=store&kind=token&kind=user&kind=variant&kind=mailinglist&kind=subscriber&kind=referral&kind=referrer&kind=transaction&kind=site&kind=deploy&kind=submission&filesystem=gs&gs_bucket_name=crowdstart-us-backup
  schedule: every 24 hours
  target: ah-builtin-python-bundle

# - description: Payout affiliates fees
#   url: /tasks/payout-affiliate
#   schedule: every 24 hours

# - description: Payout partner fees
#   url: /tasks/payout-partner
#   schedule: every 24 hours

# - description: Payout platform fees
#   url: /tasks/payout-platform
#   schedule: every 24 hours
