cron:
- description: Datastore backup (hourly)
  url: /_ah/datastore_admin/backup.create?name=automated_backup_hourly_&kind=bundle&kind=campaign&kind=collection&kind=coupon&kind=mailinglist&kind=namespace&kind=order&kind=organization&kind=payment&kind=plan&kind=product&kind=store&kind=subscriber&kind=token&kind=user&kind=variant&filesystem=gs&gs_bucket_name=crowdstart-us-backup
  schedule: every 1 hours
  target: ah-builtin-python-bundle

- description: Datastore backup (daily)
  url: /_ah/datastore_admin/backup.create?name=automated_backup_daily_&kind=bundle&kind=campaign&kind=collection&kind=coupon&kind=mailinglist&kind=namespace&kind=order&kind=organization&kind=payment&kind=plan&kind=product&kind=store&kind=subscriber&kind=token&kind=user&kind=variant&filesystem=gs&gs_bucket_name=crowdstart-us-backup
  schedule: every 1 days
  target: ah-builtin-python-bundle
