application: crowdstart-us

dispatch:
  - url: "default.hanzo.io/*"
    module: default

  - url: "js.hanzo.io/*"
    module: default

  - url: "static.hanzo.io/*"
    module: default

  - url: "a.hanzo.io/*"
    module: analytics

  - url: "cdn.hanzo.io/*"
    module: api

  - url: "api.hanzo.io/*"
    module: api

  - url: "x.hanzo.io/*"
    module: api

  - url: "dash.hanzo.io/*"
    module: dash
