application: crowdstart-us

dispatch:
  - url: "default.crowdstart.com/*"
    module: default

  - url: "js.crowdstart.com/*"
    module: default

  - url: "cdn.crowdstart.com/*"
    module: cdn

  - url: "static.crowdstart.com/*"
    module: default

  - url: "api.crowdstart.com/*"
    module: api

  - url: "www.crowdstart.com/*"
    module: platform

  - url: "a.vifijo.com/*"
    module: api
