application: crowdstart-us

dispatch:
  - url: "default.hanzo.io/*"
    module: default

  - url: "js.hanzo.io/*"
    module: default

  - url: "static.hanzo.io/*"
    module: default

  - url: "analytics.hanzo.io/*"
    module: analytics

  - url: "cdn.hanzo.io/*"
    module: api

  - url: "api.hanzo.io/*"
    module: api

  - url: "dash.hanzo.io/*"
    module: dash

  - url: "default.crowdstart.com/*"
    module: default
  - url: "js.crowdstart.com/*"
    module: default
  - url: "static.crowdstart.com/*"
    module: default

  - url: "cdn.crowdstart.com/*"
    module: api

  - url: "api.crowdstart.com/*"
    module: api
