dispatch:
  - url: "default.hanzo.io/*"
    service: default

  - url: "js.hanzo.io/*"
    service: default

  - url: "static.hanzo.io/*"
    service: default

  - url: "a.hanzo.io/*"
    service: analytics

  - url: "cdn.hanzo.io/*"
    service: api

  - url: "api.hanzo.io/*"
    service: api

  - url: "x.hanzo.io/*"
    service: api
