dispatch:
  - url: "default.hanzo.ai/*"
    service: default

  - url: "js.hanzo.ai/*"
    service: default

  - url: "static.hanzo.ai/*"
    service: default

  - url: "a.hanzo.ai/*"
    service: analytics

  - url: "api.hanzo.ai/*"
    service: api

  - url: "cdn.hanzo.ai/*"
    service: api

  - url: "x.hanzo.ai/*"
    service: api
