application: crowdstart-us

dispatch:
  - url: "js.crowdstart.com/*"
    module: default

  - url: "static.crowdstart.com/*"
    module: default

  - url: "api.crowdstart.com/*"
    module: api

  - url: "secure.crowdstart.com/*"
    module: checkout

  - url: "www.crowdstart.com/*"
    module: platform
