application: crowdstart-io

dispatch:
  - url: "static.crowdstart.io/*"
    module: default

  - url: "secure.crowdstart.io/*"
    module: checkout

  - url: "preorder.skullysystems.com/*"
    module: preorder
