queue:
- name: default
  rate: 500/s
  bucket_size: 100
  max_concurrent_requests: 50

queue:
- name: payout-platform
  rate: 100/s
  bucket_size: 100
  max_concurrent_requests: 100

queue:
- name: payout-affiliate
  rate: 100/s
  bucket_size: 100
  max_concurrent_requests: 100
