dispatch:
  - url: "*/analytics/*"
    service: analytics

  - url: "*/api/*"
    service: api

  - url: "*/dash/*"
    service: dash

  - url: "*/default/*"
    service: default

  - url: "*/static/*"
    service: default

  - url: "*/assets/*"
    service: default

  - url: "*/robots.txt"
    service: default

  - url: "*/humans.txt"
    service: default

  - url: "*/apple-touch-icon.png"
    service: default

  - url: "*/apple-touch-icon-precomposed.png"
    service: default
