application: crowdstart-io-dev
module: default

runtime: go
api_version: go1
threadsafe: true

inbound_services:
- warmup

handlers:
- url: /_ah/*
  script: _go_app

- url: /assets/*
  static_dir: ../../assets

- url: /static/*
  static_dir: ../../static

- url: /humans.txt
  static_files: ../../static/humans.txt
  upload: ../../static/humans.txt

- url: /robots.txt
  static_files: ../../static/robots.txt
  upload: ../../static/robots.txt

- url: /apple-touch-icon.png
  static_files: ../../static/apple-touch-icon.png
  upload: ../../static/apple-touch-icon.png

- url: /apple-touch-icon-precomposed.png
  static_files: ../../static/apple-touch-icon-precomposed.png
  upload: ../../static/apple-touch-icon-precomposed.png
