application: crowdstart-io-dev

dispatch:
  - url: "*/static/*"
    module: default

  - url: "*/robots.txt"
    module: default

  - url: "*/humans.txt"
    module: default

  - url: "*/favicon.ico"
    module: default

  - url: "*/api/*"
    module: api

  - url: "*/platform/*"
    module: platform

  - url: "*/checkout/*"
    module: checkout

  - url: "*/preorder/*"
    module: preorder

  - url: "*/*"
    module: store
